# Generated by Django 4.1.4 on 2023-01-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('accuracy', models.IntegerField()),
                ('weapons', models.JSONField()),
                ('items', models.JSONField()),
                ('villians', models.JSONField()),
            ],
        ),
    ]
