# Generated by Django 4.1.4 on 2023-01-10 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure_db', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaurant',
            new_name='Adventure',
        ),
    ]
